### ISSUE TITLE
What does your phone homescreen look like?

### ISSUE THREAD

**Issue by sindresorhus** [jedireza/ama#1]
Screenshot please. I ask everyone this as it tells a lot about a person. [Mine for example.](https://github.com/sindresorhus/ama/issues/64)

**Comment by jedireza** [comment]
I've been using the iPhone since v1. This week I switched to FirefoxOS (screen shot below). So I thought I'd share both :wink: 

#### iPhone

![iphone](https://cloud.githubusercontent.com/assets/979929/8575697/486e1698-2552-11e5-80e9-ab8ec81d1735.png)

#### FirefoxOS

![fxos](https://cloud.githubusercontent.com/assets/979929/8575696/486c7ae0-2552-11e5-9f39-69bce507bdf5.png)
