### ISSUE TITLE
What was the most difficult math or physics problem that you ever resolved?

### ISSUE THREAD

**Issue by aarroyoc** [jedireza/ama#15]

**Comment by jedireza** [comment]
I'm not an academic and haven't worked with physics much (at all really). Also I haven't done much with math beyond my 2nd year in high school "problem wise". In life, I've always learned what I needed, when necessary to solve whatever the problem was at that moment.

Oh and I did play with Project Euler a couple years ago.
https://github.com/jedireza/projecteuler-js
