### ISSUE TITLE
What do you do at Mozilla?

### ISSUE THREAD

**Issue by sindresorhus** [jedireza/ama#2]

**Comment by jedireza** [comment]
I just joined Mozilla last month. :tada::balloon:

I'm working on FirefoxOS. I joined the systems front-end team. Our team is responsible for the homescreen, notifications, download manager, browser, task manager and a range of other system related tasks.

I'm also implementing the front-end experience for Vaani, the new virtual assistant for FirefoxOS. It's similar in kind to Siri or Google Now, but in it's infancy and not nearly as impressive or polished as those products. But still, it's a pleasure to work on, especially since we're using an implementation of the [Web Speech API](https://dvcs.w3.org/hg/speech-api/raw-file/tip/webspeechapi.html). :grin:
