### ISSUE TITLE
What is your opinion on Dart? 

### ISSUE THREAD

**Issue by tenhobi** [jedireza/ama#25]
Dart can be used on web (compiled to JS via Dart2JS, [AngularDart](https://webdev.dartlang.org/angular/), ...), mobile ([Flutter](https://flutter.io/)), server etc.

Have you ever tried it, maybe as alternative to Javascript? What is your opinion on this language and it's platform? :-)

**Comment by jedireza** [comment]
> Have you ever tried it

No

> maybe as alternative to Javascript?

As I understand it, JavaScript is a compile target of Dart.

> What is your opinion on this language and it's platform?

I don't really have one since I haven't used it. This article has some interesting things to say about it: http://walkercoderanger.com/blog/2014/03/dart-isnt-the-answer/

Things on the web about Dart in the last year: https://www.google.com/search?q=dart+compiles+to+javascript&source=lnt&tbs=qdr:y&sa=X&ved=0ahUKEwiIx7uY08jXAhVU5GMKHYB3At4QpwUIIA&biw=1440&bih=804
