### ISSUE TITLE
What do you think of Servo?

### ISSUE THREAD

**Issue by sindresorhus** [jedireza/ama#3]
https://github.com/servo/servo

**Comment by jedireza** [comment]
Servo is an ambitious project and a pretty rad one. I don't know much more beyond the surface level stuff found in the README.

I did recently start scratching the surface with parallel/concurrent programming. I started playing with Go which is really fun. After that I checked out Rust, which I find really interesting. And since Servo is being built on Rust it's something I'm keeping my eyes on.

One thing that made me happy about the Servo project is how welcoming they are to new contributors. I also like how they have issues classified with difficulty. This can help people get their feet wet with their first contribution by starting with [easy issues](https://github.com/servo/servo/issues?q=is%3Aopen+is%3Aissue+label%3AE-easy).

**Comment by sindresorhus** [comment]
> This can help people get their feet wet with their first contribution by starting with easy issues.

It's some extra work flagging issues, but it's totally worth it.
